[package]
name = "rotsprite"
version = "0.1.2"
authors = ["Thomas Versteeg <thomasversteeg@gmx.com>"]
license = "AGPL-3.0-or-later"
edition = "2018"
readme = "README.md"
repository = "https://github.com/tversteeg/rotsprite"
documentation = "https://docs.rs/rotsprite"
description = "Rotate sprites using the rotsprite algorithm"
keywords = ["game", "sprite", "blit", "rotation"]
categories = ["rendering", "game-engines"]

[dependencies]
thiserror = "1.0.11"

[dev-dependencies]
blit = "0.5.9"
image = "0.23.0"
minifb = "0.15.3"
criterion = "0.3.1"
rand = "0.7.3"

[[bench]]
name = "rotsprite"
harness = false

[[bench]]
name = "scale2x"
harness = false

[[bench]]
name = "rotate"
harness = false
